config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'home#index'

  #about us route
  get '/about' => 'home#about'

  #sign in routes
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy', as: 'delete'


  #friendship routes
  get  '/users/:id', to: 'friendships#show', as: 'show_friendship'
  post '/users/:id/request', to: 'friendships#add', as: 'request'
  post '/users/:id/accept', to: 'friendships#accept', as: 'accept'
  post '/users/:id/decline', to: 'friendships#decline', as: 'decline'
  post '/users/:id/remove', to: 'friendships#remove', as: 'remove'
  post '/users/:id/block', to: 'friendships#block', as: 'block'
  post '/users/:id/unblock', to: 'friendships#unblock', as: 'unblock'


  #conversation/ message routes
  resources :conversations do
    resources :messages
  end

  #match form routes
  get '/users/:id/match/new', to: "users#new_match", as: 'new_match'
  post '/users/:id/match', to: "users#find_match", as: 'matches'

  #video
  get '/users/:id/video', to: "videos#create", as: 'new_video'
  # post '/users/:id/video', to: "videos#show"
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :art
  belongs_to :music
  belongs_to :sport
  belongs_to :food


  validates :first_name, :last_name, :age, presence: true
  validates :email, presence: true, confirmation: true, uniqueness: true
  validates :password, presence: true, confirmation: true, on: :create
  validates :password, length: {minimum: 5, maximum: 120}, on: :update, allow_blank: true

  has_secure_password
  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end

  has_friendship

  def friend_request?(user)
   user && !friends_with?(user) && user.id.in?(requested_friend_ids)
  end

  def requested_friend_ids
    requested_friends.pluck(:id)
  end

  def friend_pending?(user)
   user && !friends_with?(user) && user.id.in?(pending_friend_ids)
  end

  def pending_friend_ids
    pending_friends.pluck(:id)
  end

  def search_for_matches (form)
    $i = 0
    $j = 0
    matches = []
    users = User.all
    
    #finds all the users that match the form language and pushes them to matches array
    while $i < users.count do 
      while $j < users[$i].languages.count do
        if form.language == users[$i].languages[$j]
          matches.push(users[$i])
        end
        $j += 1
      end
      $j = 0
      $i+=1
    end

    $i = 0
    while $i < matches.count do 
      if form.age != nil
        if form.age == matches[$i].age
          matches[$i].count += 2
        end
      end
      if form.origin_country != ""
        if form.origin_country == matches[$i].origin_country
          matches[$i].count += 2
        end
      end
      if form.current_country != ""
        if form.current_country == matches[$i].current_country
          matches[$i].count += 2
        end
      end
      if form.male != nil
        if form.male == matches[$i].male
          matches[$i].count += 2
        end
      end
      if form.female != nil
        if form.female == matches[$i].female
          matches[$i].count += 2
        end
      end
      if form.other_gender != nil
        if form.other_gender == matches[$i].other_gender
          matches[$i].count += 2
        end
      end

      if form.interests != []
        $j = 0
        $k = 0
        while $j < form.interests.count do
          while $k < matches[$i].interests.count do
            if form.interests[$j] == matches[$i].interests[$k]
              matches[$i].count += 1
            end
            $k += 1
          end
          $k = 0
          $j += 1
        end
      end
      $i += 1
    end

    ordered_matches = matches.sort_by{|match| match[:count]}

    return ordered_matches.reverse

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    render :index
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.find(params[:id])
    if current_user == nil
      redirect_to sign_in_path
    else
      render :show
    end
  end

  # GET /users/new
  def new
    @user = User.new
    render :new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:success] = "Welcome to FAR!"
      render :edit_full_profile
    else
      redirect_to new_user_path, flash: {error: @user.errors.full_messages.to_sentence}
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    render :edit_full_profile
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    session.delete(:user_id)
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def new_match
    @match = Match.new()
    render :match_form
  end

  def find_match
    @user = current_user
    @form_match = Match.create(match_params)
    @matches = @user.search_for_matches(@form_match)
    render :matches
  end


  def match_params
    params.require(:match).permit(:language, :origin_country, :current_country, :male, :female, :other_gender, :age, :interests=>[])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params

      params.require(:user).permit(:first_name, :last_name, :email, :email_confirmation, :password, :password_confirmation, :current_city, :origin_city, :age, :occupation, :origin_country, :facebook_url, :twitter_url, :snapchat_url, :description, :why_am_i_here, :hobbies, :photo_url, :male, :female, :other_gender, :count, :current_country, :languages=>[], :interests=>[])
    end




end

app/helpers/users_helper.rb
module UsersHelper
	def countries
    	@countries
  	end

  	def countries=()
    	@countries = ["Mexico", "USA", "Italy"]
  	end
end

app/views/users/_form.html.erb
<div class="row formCard">
  <h2 class="profileTitle titles">Sign Up</h2>
  <br>
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="row form">  
      <div class="large-6 columns">
        <%= f.label :first_name, class: "formTitle" %>
        <%= f.text_field :first_name %>  
        <%= f.label :last_name, class: "formTitle" %>
        <%= f.text_field :last_name %>
        <%= f.label :email, class: "formTitle" %>
        <%= f.text_field :email %>
        <%= f.label :password, class: "formTitle" %>
        <%= f.password_field :password %>
      </div>
      <div class="large-6 columns">
        <%= f.label :age, class: "formTitle" %>
        <%= f.number_field :age %>
        <%= f.label :current_city, class: "formTitle" %>
        <%= f.text_field :current_city %>
        <%= f.label :origin_country, class: "formTitle" %>
        <%= f.text_field :origin_country %> 
        <%= f.label :current_country, class: "formTitle" %>
        <%= f.text_field :current_country %> 
      </div>
    </div>
    <br><br>
    <div class="row">
      <div class="large-12 columns large-offset-5">
        <button type="submit" class="button interests">Create Profile</button>
      </div>
    </div>
  <% end %>
</div>

app/views/users/conversation.html.erb
<h1>Matches</h1>

<h3>Hi <%= @user.first_name %></h3>

  <h2>Your search parameters:</h2> 
  <%= @conversation.language %><br>           
  <%= @conversation.origin_country %><br>
  <%= @conversation.age %><br>
  <%= @conversation.interests %>


<h2>Your matches:</h2><br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Languages</th>
      <th>Origin Country</th>
      <th>Age</th>
      <th>Interests</th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |user| %>
      <tr>
        <td><%= link_to "#{user.first_name} #{user.last_name}", "users/#{user.id}" %></td>
        <td><%= user.email %></td>
        <td><%= user.languages %></td>
        <td><%= user.origin_country %></td>
        <td><%= user.age %></td>
        <td><%= user.interests %></td>
        <td><%= user.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', new_user: false %>

<%= button_to 'User Profile', @user, class: 'button' %>
<%= button_to 'Back', users_path, class: 'button', method: :get %>

app/views/users/edit_full_profile.html.erb
<div class="row formCard">
  <h2 class="profileTitle titles">Update Profile</h2>
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="row form">  
      <div class="large-6 columns">
        <%= f.hidden_field :photo_url, role: 'uploadcare-uploader' %>
        <%= f.label :first_name, class: "formTitle" %>
        <%= f.text_field :first_name %>  
        <%= f.label :last_name, class: "formTitle" %>
        <%= f.text_field :last_name %>
        <%= f.label :email, class: "formTitle" %>
        <%= f.text_field :email %>
        <%= f.label :password, class: "formTitle" %>
        <%= f.password_field :password %>
      </div>
      <div class="large-6 columns">
        <%= f.label :age, class: "formTitle" %>
        <%= f.number_field :age %>
        <%= f.label :current_city, class: "formTitle" %>
        <%= f.text_field :current_city %>
        <%= f.label :origin_country, class: "formTitle" %>
        <%= f.text_field :origin_country %> 
        <%= f.label :current_country, class: "formTitle" %>
        <%= f.text_field :current_country %> 
      </div>
    </div>
    <div class="row form">
      <div class="large-6 columns">
        <p>Gender</p>
        <input type="radio" name="gender" value="true"> Male<br>
        <input type="radio" name="gender" value="true"> Female<br>
        <input type="radio" name="gender" value="true"> Other
      </div>
      <div class="large-6 columns">
        <%= f.label :occupation, class: "formTitle" %>
        <%= f.text_field :occupation %>
      </div>
    </div>
    <div class="row form">
      <p>Arts</p>
      <hr class="line">
      <div class="large-6 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="dancing">&emsp;Dancing</input><br>
        <input type="checkbox" name="user[interests][]" value="singing">&emsp;Singing</input><br>
        <input type="checkbox" name="user[interests][]" value="photography">&emsp;Photography</input><br>
      </div>
      <div class="large-6 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="theatre">&emsp;Theatre</input><br>
        <input type="checkbox" name="user[interests][]" value="writing">&emsp;Writing</input><br>
        <input type="checkbox" name="user[interests][]" value="painting">&emsp;Painting</input><br>
      </div>
    </div>

    <div class="row form">
      <p>Sports</p>
      <hr class="line">
      <div class="large-4 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="soccer">&emsp;Soccer</input><br>
        <input type="checkbox" name="user[interests][]" value="football">&emsp;Football</input><br>
        <input type="checkbox" name="user[interests][]" value="basketball">&emsp;Basketball</input><br>
      </div>
      <div class="large-4 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="tennis">&emsp;Tennis</input><br>
        <input type="checkbox" name="user[interests][]" value="rugby">&emsp;Rugby</input><br>
        <input type="checkbox" name="user[interests][]" value="F1">&emsp;F1</input><br>
      </div>
      <div class="large-4 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="boxing">&emsp;Boxing</input><br>
        <input type="checkbox" name="user[interests][]" value="golf">&emsp;Golf</input><br>
        <input type="checkbox" name="user[interests][]" value="baseball">&emsp;Baseball</input><br>
      </div>
    </div>

    <div class="row form">
      <p>Music</p>
      <hr class="line">
      <div class="large-3 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="pop">&emsp;Pop</input><br>
        <input type="checkbox" name="user[interests][]" value="rock">&emsp;Rock</input><br>
        <input type="checkbox" name="user[interests][]" value="randb">&emsp;R&B</input><br>
      </div>
      <div class="large-3 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="classical">&emsp;Classical</input><br>
        <input type="checkbox" name="user[interests][]" value="jazz">&emsp;Jazz</input><br>
        <input type="checkbox" name="user[interests][]" value="blues">&emsp;Blues</input><br>
      </div>
      <div class="large-3 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="folk">&emsp;Folk</input><br>
        <input type="checkbox" name="user[interests][]" value="alternative">&emsp;Alternative</input><br>
        <input type="checkbox" name="user[interests][]" value="country">&emsp;Country</input><br>
      </div>
      <div class="large-3 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="dance">&emsp;Dance</input><br>
        <input type="checkbox" name="user[interests][]" value="latin">&emsp;Latin</input><br>
        <input type="checkbox" name="user[interests][]" value="HipHop_Rap">&emsp;Hip Hop / Rap</input><br>
      </div>
    </div>

    <div class="row form">
      <p>Food</p>
      <hr class="line">
      <div class="large-4 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="italian">&emsp;Italian</input><br>
        <input type="checkbox" name="user[interests][]" value="mexican">&emsp;Mexican</input><br>
        <input type="checkbox" name="user[interests][]" value="japanese">&emsp;Japanese</input><br>
      </div>
      <div class="large-4 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="thai">&emsp;Thai</input><br>
        <input type="checkbox" name="user[interests][]" value="chinese">&emsp;Chinese</input><br>
        <input type="checkbox" name="user[interests][]" value="spanish">&emsp;Spanish</input><br>
      </div>
      <div class="large-4 columns checkbox">
        <input type="checkbox" name="user[interests][]" value="greek">&emsp;Greek</input><br>
        <input type="checkbox" name="user[interests][]" value="indian">&emsp;Indian</input><br>
        <input type="checkbox" name="user[interests][]" value="korean">&emsp;Korean</input><br>
      </div>
    </div>

    <div class="row form">
      <p>Languages</p>
      <hr class="line">
      <div class="large-4 columns radios">
        <input type="checkbox" name="user[languages][]" value="English">&emsp;English</input><br>
        <input type="checkbox" name="user[languages][]" value="Spanish">&emsp;Spanish</input><br>
        <input type="checkbox" name="user[languages][]" value="Chinese">&emsp;Chinese</input><br>
      </div>
      <div class="large-4 columns radios">
        <input type="checkbox" name="user[languages][]" value="Russian">&emsp;Russian</input><br>
        <input type="checkbox" name="user[languages][]" value="German">&emsp;German</input><br>
        <input type="checkbox" name="user[languages][]" value="French">&emsp;French</input><br>
      </div>
      <div class="large-4 columns radios">
        <input type="checkbox" name="user[languages][]" value="Italian">&emsp;Italian</input><br>
        <input type="checkbox" name="user[languages][]" value="Hindi">&emsp;Hindi</input><br>
        <input type="checkbox" name="user[languages][]" value="Japanese">&emsp;Japanese</input><br>
      </div>
    </div>

    <div class="row form">
      <%= f.label :description %>
      <%= f.text_area :description %> 

      <%= f.label :why_am_i_here %>
      <%= f.text_area :why_am_i_here %> 

      <%= f.label :hobbies %>
      <%= f.text_area :hobbies %> 
    </div>
    <div class="row">
      <div class="large-12 columns large-offset-5">
        <button type="submit" class="button">Update Profile</button>
      </div>
    </div>
  <% end %>
  <br><br>
</div>

app/views/users/index.html.erb
<div class="row">
    <div class="success callout" id="user-index-closeout" data-closable="slide-out-right">
      <h5>Find Your Best Friend Using Our Custom Search!</h5>
      <p>Looking for a best friend to visit around the world? <%= link_to "Click Here", "/users/#{current_user.id}/match/new" %> to find the perfect match!</p>
      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
</div>

<div class="row">
  <h1 class="large-6 large-centered columns" id="users-header">Find Friends!</h1>
</div>


<% @users.each do |user| %>
  <div class="media-object columns medium-6 large-4">
    <div class="media-object-section">
      <a href='/users/<%= user.id %>'><img src="<%= user.photo_url %>" class="indexUserImg"></a>
    </div>
    <div class="media-object-section">
      <h3><%= link_to user.first_name, user %></h3>
      <h4><%= user.origin_country %></h4>
      <h5>Languages:</h5>
      <p>
        <% user.languages.each do |language| %>
          <%= language %>
        <% end %>
      </p>
      <h5>Interests:</h5>
      <p>
        <% user.interests.each do |language| %>
          <%= language %>
        <% end %>
      </p>
    </div>
  </div>
<% end %>

app/views/users/matches.html.erb
<div class="row card matches">
    <h2 class="profileTitle titles">Hi, <%= @user.first_name %></h2>
    <br><br>
    
    <h2 class="profileTitle titles">Your search parameters:</h2> 
  <div class="params">
    <%= @form_match.language %><br>           
    <%= @form_match.origin_country %><br>
    <%= @form_match.age %><br>
  
    <% @form_match.interests.each do |interest| %>
      <button class="button interests"><%= interest %></button>
    <% end %>
  </div>
  
<h2>Your matches:</h2><br>

  <div class="row" id="showFriendsDiv">
    <% @matches.each do |user| %>
      <% if user.id != current_user.id %>
        <div class="columns large-2">
          <a href='/users/<%= user.id %>'><img src="<%= user.photo_url %>" class="showUserImg" ></a>
          <a href="/users/<%= user.id %>"><h6 style="text-align: center"><b><%= user.first_name %></b></h6></a>
          <h6 style="text-align: center"><%= user.current_country %></h6>
        </div>
      <% end %>
    <% end %>
  </div>  
</div>

app/views/users/new.html.erb
<%= render 'form', new_user: true %>

app/views/users/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->


<%= button_to 'Start a conversation', new_video_path, class: 'button', method: :get %>

<br><br><br>
<div class="row">
  <% if current_user.friend_request?(@user) %>
    <%= button_to 'Accept', accept_path(@user), method: :post, class: 'button' %>
    <%= button_to 'Decline', decline_path(@user), method: :post, class: 'button' %>
  <% end %>
  <% if current_user.friends_with?(@user) %>
    <%= button_to 'Send Message', conversations_path(sender_id: current_user.id, recipient_id: @user.id), class: 'button', method: :post %>
    <%= button_to 'Remove', remove_path(@user), method: :post, class: 'button' %>
  <% end %>
</div>

<div class="row">
  <div class="large-5 columns">
    <img class="profilePic" src="<%= @user.photo_url %>" alt="<%= @user.first_name %>'s Profile Pic">
  </div>
  <div class="large-7 columns">
    <div class="row">
      <h1 style="text-align: center">Hey, I'm <%= @user.first_name %></h1>
      <h5 style="text-align: center"><%= @user.current_city %>&emsp;<i class="fi-die-one"></i>&emsp; Member since <%= @user.created_at.localtime.strftime('%b %Y') %></h5>  <br><br>
    </div>
    <div class="row">
      <div class="row generalInfo">
        <div class="large-6 columns">
          <h6 class="attributes"><i class="fi-comment-quotes icons"></i>&emsp;&emsp;References</h6>
          <h6 class="attributes"><i class="fi-torso icons"></i>&emsp;&emsp;<%= @user.age %>,&ensp;
              <% if @user.male %>
                Male
              <% elsif @user.female %>
                Female
              <% else %>
                Other
              <% end %>
          </h6>
          <h6 class="attributes"><i class="fi-web icons"></i>&emsp;&emsp;
              <% @user.languages.each do |language| %>
                <%= language %>
              <% end %>
          </h6>
        </div>
        <div class="large-6 columns">
          <h6 class="attributes"><i class="fi-marker icons"></i>&emsp;&emsp;From&ensp;<%= @user.origin_country %></h6>
          <h6 class="attributes"><i class="fi-info icons"></i>&emsp;&emsp;<%= @user.occupation %></h6>
          <a href="<% @user.facebook_url %>"><h6 class="attributes"><i class="fi-social-facebook icons"></i>&emsp;&emsp;Facebook</h6></a>
        </div>
      </div>   
    </div> 
  </div>
</div>
<br>
<br>
<br>
<div class="row">
  <div class="large-1 columns">&emsp;</div>
  <div class="large-2 columns card edit end">
    <% if current_user == @user %>
      <a href="/users/<%= @user.id %>/edit"><i class="fi-pencil icons"></i>&ensp;Edit&emsp;|&emsp;</a>
      <i class="fi-trash icons"></i>&ensp;<%= link_to "Delete", @user, :method => :delete %>
    <% else %>
      <% unless current_user == @user || current_user.friends_with?(@user) || current_user.friend_pending?(@user) || current_user.friend_request?(@user) %>
      <i class="fi-torsos-all icons"></i>&ensp;<b><%= link_to 'Send Request', request_path(@user), method: :post %></b>
      <% end %>
    <% end %>
  </div>  
</div>
<br><br>
<div class="row card">
  <div class="row">
    <h2 class="profileTitle">ABOUT ME</h2>
    <div class="descriptions">
      <%= @user.description %> <br><br><br>
    </div>
    <h2 class="profileTitle">WHY AM I HERE?</h2>
    <div class="descriptions">
      <%= @user.why_am_i_here %> <br><br><br>
    </div>
    <h2 class="profileTitle">MY HOBBIES</h2>
    <div class="descriptions">
      <%= @user.hobbies %> <br><br><br>
    </div>
    <h2 class="profileTitle">INTERESTS</h2>
    <div class="">
      <div class="descriptions">
        <% @user.interests.each do |interest| %>
          <button class="button interests"><%= interest %></button>
        <% end %>
      </div>
      <br><br>
    </div>
  </div>
</div>


<div class="row card" id="showFriends">
  <div class="row">
    <div class="large-6 columns">
      <h2 class="profileTitle">FRIENDS</h2><br>
    </div>
    <% if current_user == @user %>
      <div class="large-3 columns">
        <div class="large reveal" id="modalRequests" data-reveal>
          <h3>Friend Request </h3>
          <% current_user.requested_friends.each do |q| %>
            <ul>
              <li><%= link_to q.first_name, "#{q.id}" %></li>
            </ul>
          <% end %>
        </div>
        <p><a data-open="modalRequests" style="line-height: 25px; font-size: 15px;">Friend Requests (<%= current_user.requested_friends.count %>)</a></p> 
      </div>
      <div class="large-3 columns">
        <div class="large reveal" id="modalPending" data-reveal>
          <% current_user.pending_friends.each do |q| %>
            <ul>
              <li><%= link_to q.first_name, "#{q.id}" %></li>
            </ul>
          <% end %>
        </div>
        <p><a data-open="modalPending" style="line-height: 25px; font-size: 15px;">Pending Requests(<%= current_user.pending_friends.count %>)</a></p>
      </div>
    <% end %>
  </div>  
  <div class="row" id="showFriendsDiv">
    <% @user.friends.each do |friend| %>
      <div class="columns large-2">
        <a href='/users/<%= friend.id %>'><img src="<%= friend.photo_url %>" class="showUserImg" ></a>
        <a href="/users/<%= friend.id %>"><h6 style="text-align: center"><b><%= friend.first_name %></b></h6></a>
        <h6 style="text-align: center"><%= friend.current_country %></h6>
      </div>
    <% end %>
  </div>  
</div>

<div class="row card">
 <h3>Friend Request </h3>
 <% current_user.requested_friends.each do |q| %>
   <ul>
     <li><%= link_to q.first_name, "#{q.id}" %></li>
   </ul>
 <% end %>


 <h3>Pending Friends</h3>
 <% current_user.pending_friends.each do |p| %>
   <ul>
     <li><%= link_to p.first_name, "#{p.id}" %></li>
   </ul>
 <% end %>


</div>