config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'home#index'

  #about us route
  get '/about' => 'home#about'

  #sign in routes
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy', as: 'delete'


  #friendship routes
  get  '/users/:id', to: 'friendships#show', as: 'show_friendship'
  post '/users/:id/request', to: 'friendships#add', as: 'request'
  post '/users/:id/accept', to: 'friendships#accept', as: 'accept'
  post '/users/:id/decline', to: 'friendships#decline', as: 'decline'
  post '/users/:id/remove', to: 'friendships#remove', as: 'remove'
  post '/users/:id/block', to: 'friendships#block', as: 'block'
  post '/users/:id/unblock', to: 'friendships#unblock', as: 'unblock'


  #conversation/ message routes
  resources :conversations do
    resources :messages
  end

  #match form routes
  get '/users/:id/match/new', to: "users#new_match", as: 'new_match'
  post '/users/:id/match', to: "users#find_match", as: 'matches'

  #video
  get '/users/:id/video', to: "videos#create", as: 'new_video'
  # post '/users/:id/video', to: "videos#show"
end

app/controllers/home_controller.rb
# require 'opentok'

# opentok = OpenTok::OpenTok.new '45613842', 'be0aa1632ada533cbc168e5ca79a32c28ad5c3f2'

class HomeController < ApplicationController
  def index
  	# @session = opentok.create_session
   #  @token = session.generate_token
    render :home
  end

  def about
  	render :about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1 align="center">About Us</h1>
    
   <div class="row">
     
     <div class="medium-4 columns"><%= image_tag("World-Flags-Globe.png", :alt => "flag globe") %></div>
     
   </div>
   <br>
   <div class="row">
    
     <div class="callout primary">
      
       <p>Hello, we are Friends Around the World, aka FAR, and we are a cultural and language site that helps people connect and make new friends from around the world who share their language and cultural interests. We wanted to have a place for our members to meet new friends that share their love of language and world culture and that is why we created FAR.</p><br>
       <p>You can create a free account, update your profile and begin exploring our site, by making friends with people who share your language, or with people who speak a language that you want to learn. All you have to do is send a request to a potential friend or search for matching intersts. You can talk to your friends via private message, or even via video chat.</p>
      </div>
     </div>
     <div class="col-sm-1"></div>
   </div>
  <br><br><br><br><br><br>
   <h1 align="center">Developers</h1>

   <br>
   <div class="row">
     <div class="small-3 columns"><%= image_tag("kabah.jpeg", :alt => "photo of kabah", :class => "indexUserImg") %></div>
     <div class="small-3 columns"><%= image_tag("kate.jpeg", :alt => "photo of kate", :class => "indexUserImg") %></div>
     <div class="small-3 columns"><%= image_tag("emilio.jpeg", :alt => "photo of emilio", :class => "indexUserImg") %></div>
     <div class="small-3 columns"><%= image_tag("valerie.jpg", :alt => "photo of valerie", :class => "indexUserImg") %></div>
     
   </div>


   <div class="row">
     <div class="small-3 columns" style="text-align: center">
       <h4>Kabah Conda</h4>
        <a href="https://github.com/kabah">GitHub</a>
     </div>
     <div class="small-3 columns" style="text-align: center">
       <h4>Kate Nelson</h4>
        <a href="https://github.com/mkatenelson">GitHub</a>
     </div>
     <div class="small-3 columns" style="text-align: center">
       <h4>Emilio Gomez</h4>
        <a href="https://github.com/emiliogomezlavin">Github</a>
       </ul>
     </div>
     <div class="small-3 columns" style="text-align: center">
       <h4>Valerie Fredericks</h4>
      <a href="https://github.com/glinraen">Github</a>
     </div>
   </div>
  </div>
  <br><br>

app/views/home/home.html.erb
<!-- <img class="mySlides" src="https://upload.wikimedia.org/wikipedia/commons/3/3d/Dubrovnik_-_Croatia.jpg">
<img class="mySlides" src="http://braziltouroperator.com/infinitysas/wp-content/uploads/2015/11/1418827135_lama-and-machu-picchu-peru-1600x1067.jpg">
<img class="mySlides" src="https://upload.wikimedia.org/wikipedia/commons/b/b6/Pha_That_Luang,_Vientiane,_Laos.jpg"> -->

<div class="orbit" role="region" aria-label="Travel Pictures" data-orbit data-use-m-u-i="false">
  <ul class="orbit-container">
    <button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
    <button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>

      <li class="is-active orbit-slide">
        <img class="orbit-image" src="https://upload.wikimedia.org/wikipedia/commons/3/3d/Dubrovnik_-_Croatia.jpg" alt="Space">
        <figcaption class="orbit-caption">
          <h1 align="center"><strong>Friends Around the World</strong></h1>
          <h4 align="center">Discover the World in Your Free Time</h4>
        </div>
      </div>

      <div class="row">
        <div class="home-text">

            <p class="home-text">We are a cultural and language site that helps people connect and make new friends around the world who share their language and cultural interests.<br>
              <br>
            <strong>How it works:</strong><br>
            <br>
            Sign-up to create a profile. Then, you can get started finding friends who either speak a language you want to learn or live in a part of the world that you are interested in.  You can either find them by interests that match yours or that you want to learn about. Once you have a list of some potential friends who match your criteria, you can contact them by either sending friend request. Once they accept, you can start talking, either by video or private message.<br>
            <br>
            It’s free and secure to sign up. Get started finding new friends today by clicking the link to start your profile.</p>

        </figcaption>
        <div class="button-group">
          <%= button_to "Login", sign_in_path, method: :get, class: "button" %>
          <%= button_to "Sign Up", new_user_path, method: :get, class: "button" %>
        </div>
      </li>

  </ul>
</div>