config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'home#index'

  #about us route
  get '/about' => 'home#about'

  #sign in routes
  get '/sign_in', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/sessions', to: 'sessions#destroy', as: 'delete'


  #friendship routes
  get  '/users/:id', to: 'friendships#show', as: 'show_friendship'
  post '/users/:id/request', to: 'friendships#add', as: 'request'
  post '/users/:id/accept', to: 'friendships#accept', as: 'accept'
  post '/users/:id/decline', to: 'friendships#decline', as: 'decline'
  post '/users/:id/remove', to: 'friendships#remove', as: 'remove'
  post '/users/:id/block', to: 'friendships#block', as: 'block'
  post '/users/:id/unblock', to: 'friendships#unblock', as: 'unblock'


  #conversation/ message routes
  resources :conversations do
    resources :messages
  end

  #match form routes
  get '/users/:id/match/new', to: "users#new_match", as: 'new_match'
  post '/users/:id/match', to: "users#find_match", as: 'matches'

  #video
  get '/users/:id/video', to: "videos#create", as: 'new_video'
  # post '/users/:id/video', to: "videos#show"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if !current_user
      redirect_to sign_in_path, notice: "You must be signed in to do that!"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<!-- Nav Bar -->
<div class="top-bar">
  <div class="top-bar-left">

    <a href="/" class="menu-text">Friends Around the World</a>

  </div>

  <div class="top-bar-right">
    <ul class="menu">
      <% if current_user %>
        <li class="menu"><%= button_to 'My Profile', user_path(current_user), method: :get, class: "button" %></li>
        <li class="menu"><%= button_to "Members", users_path, method: :get, class: "button" %></li>
        <li class="menu"><%= button_to "Messages", conversations_path, class: "button", method: :get %></li>
        <li class="menu"><%= button_to "Search", "/users/#{current_user.id}/match/new", class: "button", method: :get %></li>
        <li class="menu"><%= button_to "Sign Out", sessions_path, method: :delete, class: "button" %></li>
      <% else %>
        <li class="menu"><%= button_to "Login", sign_in_path, method: :get, class: "button" %></li>
        <li class="menu"><%= button_to "Sign up", new_user_path, method: :get, class: "button" %></li>
      <% end %>
      <li class="menu"><%= button_to "About Us", about_path, method: :get, class: "button" %></li>
    </ul>
  </div>
</div>